name: Cortex CLI Code Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
  CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
  CORTEX_API_URL: https://api-viso-cythskzmn2uumzxldjkupd.xdr-qa2-uat.us.paloaltonetworks.com
  CORTEX_CLI_VERSION: 0.11.8

jobs:
  cortex-code-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Temporary Token
        run: |
          echo "Fetching temporary token..."
          TOKEN_RESPONSE=$(curl --silent --fail --location "${CORTEX_API_URL}/public_api/v1/unified-cli/image/token" \
            --header "Authorization: ${CORTEX_API_KEY}" \
            --header "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" \
            --header 'Content-Type: application/json' \
            --data '{}')

          echo "Response: $TOKEN_RESPONSE"

          TEMP_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.token')
          if [ -z "$TEMP_TOKEN" ] || [ "$TEMP_TOKEN" = "null" ]; then
            echo "❌ No valid TEMP_TOKEN received."
            exit 1
          fi

          echo "TEMP_TOKEN=$TEMP_TOKEN" >> $GITHUB_ENV
          echo "✅ TEMP_TOKEN set."

      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image with TEMP_TOKEN=$TEMP_TOKEN"
          docker pull distributions-dev.traps.paloaltonetworks.com/cli-docker/$TEMP_TOKEN/method:amd64-${CORTEX_CLI_VERSION}-dev
          docker tag distributions-dev.traps.paloaltonetworks.com/cli-docker/$TEMP_TOKEN/method:amd64-${CORTEX_CLI_VERSION}-dev cortexcli:${CORTEX_CLI_VERSION}
          echo "✅ Docker image pulled and tagged."

      - name: Run Docker Container
        run: |
          echo "Running Cortex CLI code scan..."
          docker run --rm -v ${{ github.workspace }}:/home/code cortexcli:${{ env.CORTEX_CLI_VERSION }} \
            --api-base-url ${CORTEX_API_URL} \
            --api-key ${CORTEX_API_KEY} \
            --api-key-id ${CORTEX_API_KEY_ID} \
            code scan \
            --directory /home/code \
            --repo-id ${{ github.repository }} \
            --branch ${{ github.ref_name }} \
            --source 'GITHUB_ACTIONS' \
            --create-repo-if-missing
          echo "✅ Code scan completed."
